package:
  name: scyjava
  version: 0.1.0

source:
  git_url: https://github.com/scijava/scyjava
  git_rev: 0.1.0

build:
  number: 0
  noarch: python
  script: pip install --no-deps .

requirements:
 build:
   - pip
   - pyjnius
 run:
   # require openjdk and maven? I'd rather have those as optional dependencies
   # they are currently required through pyjnius, though
   # - openjdk >=8
   # - maven
   - python {{PY_VER}}*
   - pyjnius
   - jgo

about:
  home: https://github.com/scijava/scyjava
