export FIJI_APP_DIR_CONDA_BACKUP=$FIJI_APP_DIR
export FIJI_APP_DIR="${CONDA_PREFIX}/share/Fiji.app"
export FIJI_JARS_CONDA_BACKUP=$FIJI_JARS
export FIJI_JARS="${FIJI_APP_DIR}/jars/*:${FIJI_APP_DIR}/plugins/*"
