package:
  name: imglyb
  version: 0.3.3_dev

source:
  git_url: https://github.com/imglib/imglyb
  git_rev: 5248c122a2ee1ab528fd9ec70700433a43602f85

build:
  number: 0
  noarch: python
  script: pip install --no-deps .

requirements:
 build:
   - pip
 run:
   # require openjdk and maven? I'd rather have those as optional dependencies
   # - openjdk >=8
   # - maven
   - python {{PY_VER}}*
   - numpy
   - pyjnius
   - scyjava
   - pyobjc-core              # [osx]
   - pyobjc-framework-cocoa   # [osx]

about:
  home: https://github.com/imglib/imglyb
