package:
  name: jrun

  version: 0.1.0dev

source:
  git_url: https://github.com/hanslovsky/jrun
  git_rev: 926cbed2c2768b308fce951a340d50e474e46605

build:
  number: 0
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - jrun = jrun.jrun:jrun_main

requirements:
 host:
   - python
   - pip
 run:
   - python
   
about:
  home: https://github.com/hanslovsky/jrun/tree/python
