package:
  name: paintera

  version: 0.13.0

source:
  path: paintera

build:
  number: 0
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - paintera                   = paintera:jgo_paintera
    - paintera-show-container    = paintera:jgo_paintera_show_container

requirements:
 host:
   - python
   - pip
 run:
   - python
   - jgo
   - psutil
   - paintera-conversion-helper >=0.4.0
   
about:
  home: https://github.com/saalfeldlab/paintera
