package:
  name: paintera

  version: 0.1.0

source:
  path: paintera

build:
  number: 0
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - paintera = paintera:jrun_paintera

requirements:
 host:
   - python
   - pip
 run:
   - python
   - jrun
   
about:
  home: https://github.com/saalfeldlab/paintera
