package:
  name: paintera

  version: 0.5.1

source:
  path: paintera

build:
  number: 0
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - paintera                   = paintera:jrun_paintera
    - paintera-show-container    = paintera:jrun_paintera_show_container
    - paintera-conversion-helper = paintera:jrun_paintera_conversion_helper

requirements:
 host:
   - python
   - pip
 run:
   - python
   - jrun
   - psutil
   
about:
  home: https://github.com/saalfeldlab/paintera
