package:
  name: sportsplex-utilities

  {% set tagged_version = GIT_DESCRIBE_TAG %}
  # If current revision is not tagged add number of commits since last tag to version.
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
  {% endif %}

  version: {{tagged_version}}

source:
  git_url: https://github.com/hanslovsky/sportsplex-utilities.git
  git_rev: master

build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - convert-schedule = sportsplex.convert_schedule:main

requirements:
 build:
   - pip
   - git
   - python
 run:
   - beautifulsoup4
   - requests

about:
  home: https://github.com/hanslovsky/sportsplex-utilities
