package:
  name: jgo

  version: 0.1.0

source:
  git_url: https://github.com/scijava/jgo
  git_rev: 0.1.0

build:
  number: 0
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - jgo = jgo.jgo:jgo_main

requirements:
 host:
   - python
   - pip
 run:
   - python

about:
  home: https://github.com/scijava/jgo
