package:
  name: imagey

  version: 0.1.1

source:
  git_url: https://github.com/hanslovsky/imagey
  git_rev: 0.1.1

build:
  number: 0
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - imagey = imagey.imagey:main

requirements:
 # currently requires maven on building host. Once all dependencies are present in maven repositories AND a usable maven conda package exists, use conda maven for build.
 host:
   - python
   - pip
 run:
   - python
   - numpy
   - pyjnius
   - imglib2-imglyb
   - qtconsole
   - pyqt=5
   
about:
  home: https://github.com/hanslovsky/imagey
