package:
  name: paintera-conversion-helper

  version: 0.5.1

source:
  path: paintera_conversion_helper

build:
  number: 2
  noarch: python
  script: pip install --no-deps .
  entry_points:
    - paintera-conversion-helper = paintera_conversion_helper:jgo_paintera_conversion_helper

requirements:
 host:
   - python
   - pip
 run:
   - python
   - jgo
   - psutil
   
about:
  home: https://github.com/saalfeldlab/paintera-conversion-helper
